--------------------------------------------------------------------------------
-- SPRINT 2 - EasyPark (Oracle)
-- Itens: 
-- 1 (correções)
-- 2 (validações)
-- 3 (CRUD)
-- 5 (função cursor+joins)
-- 6 (função regra)
--------------------------------------------------------------------------------

-----------------------------
-- ITEM 1: CORREÇÕES SPRINT 1
-----------------------------

-- 1.1 Criação do domínio de endereço (UF, CIDADE, BAIRRO, ENDERECO)
CREATE TABLE uf (
  sigla VARCHAR2(2) PRIMARY KEY,
  nome  VARCHAR2(50) NOT NULL
);

CREATE TABLE cidade (
  id       NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome     VARCHAR2(80) NOT NULL,
  uf_sigla VARCHAR2(2)  NOT NULL REFERENCES uf(sigla),
  CONSTRAINT uq_cidade_nome_uf UNIQUE (nome, uf_sigla)
);

CREATE TABLE bairro (
  id        NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nome      VARCHAR2(80) NOT NULL,
  cidade_id NUMBER       NOT NULL REFERENCES cidade(id) ON DELETE CASCADE,
  CONSTRAINT uq_bairro_nome_cidade UNIQUE (nome, cidade_id)
);

CREATE TABLE endereco (
  id           NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cep          VARCHAR2(10),
  logradouro   VARCHAR2(150),
  numero       VARCHAR2(20),
  complemento  VARCHAR2(50),
  bairro_id    NUMBER REFERENCES bairro(id) ON DELETE SET NULL,
  latitude     NUMBER(9,6),
  longitude    NUMBER(9,6)
);
CREATE INDEX idx_endereco_bairro ON endereco(bairro_id);
CREATE INDEX idx_endereco_cep    ON endereco(cep);

-- 1.2 Estacionamento passa a referenciar endereço e remove colunas achatadas
ALTER TABLE estacionamento ADD (endereco_id NUMBER);
ALTER TABLE estacionamento
  ADD CONSTRAINT fk_est_endereco
  FOREIGN KEY (endereco_id) REFERENCES endereco(id);

ALTER TABLE estacionamento DROP COLUMN endereco;
ALTER TABLE estacionamento DROP COLUMN latitude;
ALTER TABLE estacionamento DROP COLUMN longitude;

-- 1.3 Pagamento_pagador passa a referenciar endereço e remove colunas achatadas
ALTER TABLE pagamento_pagador ADD (endereco_id NUMBER);
ALTER TABLE pagamento_pagador
  ADD CONSTRAINT fk_ppag_endereco
  FOREIGN KEY (endereco_id) REFERENCES endereco(id);

ALTER TABLE pagamento_pagador DROP COLUMN cep;
ALTER TABLE pagamento_pagador DROP COLUMN logradouro;
ALTER TABLE pagamento_pagador DROP COLUMN numero;
ALTER TABLE pagamento_pagador DROP COLUMN complemento;
ALTER TABLE pagamento_pagador DROP COLUMN bairro;
ALTER TABLE pagamento_pagador DROP COLUMN cidade;
ALTER TABLE pagamento_pagador DROP COLUMN uf;

-----------------------------
-- ITEM 2: FUNÇÕES DE VALIDAÇÃO
-----------------------------

-- 2.1 Validação CPF/CNPJ: retorna 1 (ok) / 0 (inválido)
CREATE OR REPLACE FUNCTION fn_validar_cpf_cnpj(p_doc IN VARCHAR2)
RETURN NUMBER DETERMINISTIC IS
BEGIN
  IF p_doc IS NULL THEN RETURN 0; END IF;
  IF REGEXP_LIKE(p_doc, '^[0-9]{11}$') THEN
    RETURN 1;
  ELSIF REGEXP_LIKE(p_doc, '^[0-9]{14}$') THEN
    RETURN 1;
  ELSE
    RETURN 0;
  END IF;
END;
/
SHOW ERRORS

-- 2.2 Validação de e-mail: retorna 1 (ok) / 0 (inválido)
CREATE OR REPLACE FUNCTION fn_validar_email(p_email IN VARCHAR2)
RETURN NUMBER DETERMINISTIC IS
BEGIN
  IF p_email IS NULL THEN RETURN 0; END IF;
  IF REGEXP_LIKE(p_email, '^[A-Za-z0-9._%+\-]+@[A-Za-z0-9.\-]+\.[A-Za-z]{2,}$') THEN
    RETURN 1;
  ELSE
    RETURN 0;
  END IF;
END;
/
SHOW ERRORS

-- 2.3 Validação de antecedência escolhida pelo usuário (respeita regras do estacionamento e suspensão)
--     Retorna 1 (ok) / 0 (inválido)
CREATE OR REPLACE FUNCTION fn_validar_antecedencia(
  p_estacionamento_id   IN NUMBER,
  p_usuario_id          IN NUMBER,
  p_antecedencia_min    IN NUMBER
) RETURN NUMBER IS
  v_max_normal    NUMBER;
  v_max_suspenso  NUMBER;
  v_susp_ate      TIMESTAMP WITH TIME ZONE;
  v_hoje          TIMESTAMP WITH TIME ZONE := SYSTIMESTAMP;
BEGIN
  IF p_antecedencia_min IS NULL OR p_antecedencia_min < 0 THEN
    RETURN 0;
  END IF;

  SELECT max_antecedencia_minutos, max_antecedencia_minutos_suspenso
    INTO v_max_normal, v_max_suspenso
    FROM estacionamento
   WHERE id = p_estacionamento_id;

  SELECT suspensao_ate
    INTO v_susp_ate
    FROM usuario
   WHERE id = p_usuario_id;

  IF v_susp_ate IS NOT NULL AND v_susp_ate > v_hoje THEN
    RETURN CASE WHEN p_antecedencia_min <= NVL(v_max_suspenso, v_max_normal) THEN 1 ELSE 0 END;
  ELSE
    RETURN CASE WHEN p_antecedencia_min <= v_max_normal THEN 1 ELSE 0 END;
  END IF;
EXCEPTION
  WHEN NO_DATA_FOUND THEN
    RETURN 0;
END;
/
SHOW ERRORS

-----------------------------
-- ITEM 3: CRUDs PADRONIZADOS (com validação e tratamento de erros)
-- Observações:
--  * Todas as procedures não fazem COMMIT.
--  * Use raise_application_error(-2000X, 'mensagem').
--  * Em INSERT/UPDATE, usamos as funções de validação quando aplicável.
-----------------------------

-- UF
CREATE OR REPLACE PROCEDURE uf_ins(p_sigla IN VARCHAR2, p_nome IN VARCHAR2) IS
BEGIN
  IF p_sigla IS NULL OR NOT REGEXP_LIKE(p_sigla,'^[A-Z]{2}$') THEN
    raise_application_error(-20001,'UF inválida: use duas letras maiúsculas.');
  END IF;
  INSERT INTO uf(sigla, nome) VALUES (p_sigla, p_nome);
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN
  raise_application_error(-20001,'UF já existente.');
END;
/
CREATE OR REPLACE PROCEDURE uf_upd(p_sigla IN VARCHAR2, p_nome IN VARCHAR2) IS
BEGIN
  UPDATE uf SET nome = p_nome WHERE sigla = p_sigla;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'UF não encontrada.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE uf_del(p_sigla IN VARCHAR2) IS
BEGIN
  DELETE FROM uf WHERE sigla = p_sigla;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'UF não encontrada.'); END IF;
END;
/

-- CIDADE
CREATE OR REPLACE PROCEDURE cidade_ins(p_nome IN VARCHAR2, p_uf_sigla IN VARCHAR2, p_id OUT NUMBER) IS
BEGIN
  INSERT INTO cidade(nome, uf_sigla) VALUES (p_nome, p_uf_sigla)
  RETURNING id INTO p_id;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    raise_application_error(-20001,'Cidade já existe na UF.');
  WHEN NO_DATA_FOUND THEN
    raise_application_error(-20001,'UF inexistente.');
END;
/
CREATE OR REPLACE PROCEDURE cidade_upd(p_id IN NUMBER, p_nome IN VARCHAR2, p_uf_sigla IN VARCHAR2) IS
BEGIN
  UPDATE cidade SET nome = p_nome, uf_sigla = p_uf_sigla WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Cidade não encontrada.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE cidade_del(p_id IN NUMBER) IS
BEGIN
  DELETE FROM cidade WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Cidade não encontrada.'); END IF;
END;
/

-- BAIRRO
CREATE OR REPLACE PROCEDURE bairro_ins(p_nome IN VARCHAR2, p_cidade_id IN NUMBER, p_id OUT NUMBER) IS
BEGIN
  INSERT INTO bairro(nome, cidade_id) VALUES (p_nome, p_cidade_id)
  RETURNING id INTO p_id;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN raise_application_error(-20001,'Bairro já existe na cidade.');
  WHEN NO_DATA_FOUND THEN raise_application_error(-20001,'Cidade inexistente.');
END;
/
CREATE OR REPLACE PROCEDURE bairro_upd(p_id IN NUMBER, p_nome IN VARCHAR2, p_cidade_id IN NUMBER) IS
BEGIN
  UPDATE bairro SET nome = p_nome, cidade_id = p_cidade_id WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Bairro não encontrado.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE bairro_del(p_id IN NUMBER) IS
BEGIN
  DELETE FROM bairro WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Bairro não encontrado.'); END IF;
END;
/

-- ENDERECO
CREATE OR REPLACE PROCEDURE endereco_ins(
  p_cep IN VARCHAR2, p_logradouro IN VARCHAR2, p_numero IN VARCHAR2, p_complemento IN VARCHAR2,
  p_bairro_id IN NUMBER, p_lat IN NUMBER, p_lng IN NUMBER, p_id OUT NUMBER
) IS
BEGIN
  INSERT INTO endereco(cep, logradouro, numero, complemento, bairro_id, latitude, longitude)
  VALUES (p_cep, p_logradouro, p_numero, p_complemento, p_bairro_id, p_lat, p_lng)
  RETURNING id INTO p_id;
END;
/
CREATE OR REPLACE PROCEDURE endereco_upd(
  p_id IN NUMBER, p_cep IN VARCHAR2, p_logradouro IN VARCHAR2, p_numero IN VARCHAR2, p_complemento IN VARCHAR2,
  p_bairro_id IN NUMBER, p_lat IN NUMBER, p_lng IN NUMBER
) IS
BEGIN
  UPDATE endereco
     SET cep = p_cep, logradouro = p_logradouro, numero = p_numero, complemento = p_complemento,
         bairro_id = p_bairro_id, latitude = p_lat, longitude = p_lng
   WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Endereço não encontrado.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE endereco_del(p_id IN NUMBER) IS
BEGIN
  DELETE FROM endereco WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Endereço não encontrado.'); END IF;
END;
/

-- OPERADORA
CREATE OR REPLACE PROCEDURE operadora_ins(
  p_cnpj IN VARCHAR2, p_razao IN VARCHAR2, p_fantasia IN VARCHAR2, p_tel IN VARCHAR2, p_id OUT NUMBER
) IS
BEGIN
  INSERT INTO operadora(cnpj, razao_social, nome_fantasia, telefone, criado_em)
  VALUES(p_cnpj, p_razao, p_fantasia, p_tel, SYSTIMESTAMP)
  RETURNING id INTO p_id;
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN
  raise_application_error(-20001,'CNPJ já cadastrado.');
END;
/
CREATE OR REPLACE PROCEDURE operadora_upd(
  p_id IN NUMBER, p_cnpj IN VARCHAR2, p_razao IN VARCHAR2, p_fantasia IN VARCHAR2, p_tel IN VARCHAR2
) IS
BEGIN
  UPDATE operadora SET cnpj=p_cnpj, razao_social=p_razao, nome_fantasia=p_fantasia, telefone=p_tel
   WHERE id=p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Operadora não encontrada.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE operadora_del(p_id IN NUMBER) IS
BEGIN
  DELETE FROM operadora WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Operadora não encontrada.'); END IF;
END;
/

-- ESTACIONAMENTO
CREATE OR REPLACE PROCEDURE estacionamento_ins(
  p_operadora_id IN NUMBER, p_nome IN VARCHAR2, p_endereco_id IN NUMBER,
  p_espera IN NUMBER, p_tol IN NUMBER, p_limite_no_show IN NUMBER,
  p_max_ant IN NUMBER, p_max_ant_susp IN NUMBER, p_id OUT NUMBER
) IS
BEGIN
  INSERT INTO estacionamento(operadora_id, nome, endereco_id, espera_minutos, tolerancia_minutos,
                             limite_no_show, max_antecedencia_minutos, max_antecedencia_minutos_suspenso, criado_em)
  VALUES (p_operadora_id, p_nome, p_endereco_id, p_espera, p_tol, p_limite_no_show, p_max_ant, p_max_ant_susp, SYSTIMESTAMP)
  RETURNING id INTO p_id;
END;
/
CREATE OR REPLACE PROCEDURE estacionamento_upd(
  p_id IN NUMBER, p_nome IN VARCHAR2, p_endereco_id IN NUMBER,
  p_espera IN NUMBER, p_tol IN NUMBER, p_limite_no_show IN NUMBER,
  p_max_ant IN NUMBER, p_max_ant_susp IN NUMBER
) IS
BEGIN
  UPDATE estacionamento
     SET nome = p_nome, endereco_id = p_endereco_id, espera_minutos = p_espera,
         tolerancia_minutos = p_tol, limite_no_show = p_limite_no_show,
         max_antecedencia_minutos = p_max_ant, max_antecedencia_minutos_suspenso = p_max_ant_susp
   WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Estacionamento não encontrado.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE estacionamento_del(p_id IN NUMBER) IS
BEGIN
  DELETE FROM estacionamento WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Estacionamento não encontrado.'); END IF;
END;
/

-- NIVEL
CREATE OR REPLACE PROCEDURE nivel_ins(p_estacionamento_id IN NUMBER, p_nome IN VARCHAR2, p_ordem IN NUMBER, p_id OUT NUMBER) IS
BEGIN
  INSERT INTO nivel(estacionamento_id, nome, ordem, criado_em)
  VALUES (p_estacionamento_id, p_nome, p_ordem, SYSTIMESTAMP)
  RETURNING id INTO p_id;
END;
/
CREATE OR REPLACE PROCEDURE nivel_upd(p_id IN NUMBER, p_nome IN VARCHAR2, p_ordem IN NUMBER) IS
BEGIN
  UPDATE nivel SET nome = p_nome, ordem = p_ordem WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Nível não encontrado.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE nivel_del(p_id IN NUMBER) IS
BEGIN
  DELETE FROM nivel WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Nível não encontrado.'); END IF;
END;
/

-- TIPO_VAGA
CREATE OR REPLACE PROCEDURE tipo_vaga_ins(
  p_nome IN VARCHAR2, p_eletrica IN CHAR, p_acessivel IN CHAR, p_moto IN CHAR, p_tarifa IN NUMBER, p_id OUT NUMBER
) IS
BEGIN
  INSERT INTO tipo_vaga(nome, eh_eletrica, eh_acessivel, eh_moto, tarifa_por_minuto)
  VALUES (p_nome, p_eletrica, p_acessivel, p_moto, p_tarifa)
  RETURNING id INTO p_id;
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN
  raise_application_error(-20001,'Tipo de vaga já existe.');
END;
/
CREATE OR REPLACE PROCEDURE tipo_vaga_upd(
  p_id IN NUMBER, p_nome IN VARCHAR2, p_eletrica IN CHAR, p_acessivel IN CHAR, p_moto IN CHAR, p_tarifa IN NUMBER
) IS
BEGIN
  UPDATE tipo_vaga SET nome=p_nome, eh_eletrica=p_eletrica, eh_acessivel=p_acessivel, eh_moto=p_moto, tarifa_por_minuto=p_tarifa
   WHERE id=p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Tipo de vaga não encontrado.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE tipo_vaga_del(p_id IN NUMBER) IS
BEGIN
  DELETE FROM tipo_vaga WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Tipo de vaga não encontrado.'); END IF;
END;
/

-- VAGA
CREATE OR REPLACE PROCEDURE vaga_ins(p_nivel_id IN NUMBER, p_codigo IN VARCHAR2, p_tipo_vaga_id IN NUMBER, p_ativa IN CHAR, p_id OUT NUMBER) IS
BEGIN
  INSERT INTO vaga(nivel_id, codigo, tipo_vaga_id, ativa, criado_em)
  VALUES (p_nivel_id, p_codigo, p_tipo_vaga_id, p_ativa, SYSTIMESTAMP)
  RETURNING id INTO p_id;
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN
  raise_application_error(-20001,'Código de vaga já existe neste nível.');
END;
/
CREATE OR REPLACE PROCEDURE vaga_upd(p_id IN NUMBER, p_codigo IN VARCHAR2, p_tipo_vaga_id IN NUMBER, p_ativa IN CHAR) IS
BEGIN
  UPDATE vaga SET codigo=p_codigo, tipo_vaga_id=p_tipo_vaga_id, ativa=p_ativa WHERE id=p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Vaga não encontrada.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE vaga_del(p_id IN NUMBER) IS
BEGIN
  DELETE FROM vaga WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Vaga não encontrada.'); END IF;
END;
/

-- SENSOR
CREATE OR REPLACE PROCEDURE sensor_ins(p_vaga_id IN NUMBER, p_modelo IN VARCHAR2, p_ident IN VARCHAR2, p_ativo IN CHAR, p_config IN VARCHAR2, p_id OUT NUMBER) IS
BEGIN
  INSERT INTO sensor(vaga_id, modelo, identificador_externo, ativo, config, criado_em)
  VALUES (p_vaga_id, p_modelo, p_ident, p_ativo, p_config, SYSTIMESTAMP)
  RETURNING id INTO p_id;
END;
/
CREATE OR REPLACE PROCEDURE sensor_upd(p_id IN NUMBER, p_modelo IN VARCHAR2, p_ident IN VARCHAR2, p_ativo IN CHAR, p_config IN VARCHAR2) IS
BEGIN
  UPDATE sensor SET modelo=p_modelo, identificador_externo=p_ident, ativo=p_ativo, config=p_config WHERE id=p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Sensor não encontrado.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE sensor_del(p_id IN NUMBER) IS
BEGIN
  DELETE FROM sensor WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Sensor não encontrado.'); END IF;
END;
/

-- VAGA_STATUS (cache) - CRUD simples
CREATE OR REPLACE PROCEDURE vaga_status_ins(p_vaga_id IN NUMBER, p_status IN VARCHAR2, p_ts IN TIMESTAMP WITH TIME ZONE, p_sensor_id IN NUMBER) IS
BEGIN
  INSERT INTO vaga_status(vaga_id, status_ocupacao, ultimo_ocorrido, sensor_id)
  VALUES (p_vaga_id, p_status, p_ts, p_sensor_id);
END;
/
CREATE OR REPLACE PROCEDURE vaga_status_upd(p_vaga_id IN NUMBER, p_status IN VARCHAR2, p_ts IN TIMESTAMP WITH TIME ZONE, p_sensor_id IN NUMBER) IS
BEGIN
  UPDATE vaga_status SET status_ocupacao=p_status, ultimo_ocorrido=p_ts, sensor_id=p_sensor_id
   WHERE vaga_id=p_vaga_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Vaga_status não encontrado.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE vaga_status_del(p_vaga_id IN NUMBER) IS
BEGIN
  DELETE FROM vaga_status WHERE vaga_id = p_vaga_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Vaga_status não encontrado.'); END IF;
END;
/

-- SENSOR_EVENTO (histórico – normalmente só INSERT/DELETE; UPDATE para correção)
CREATE OR REPLACE PROCEDURE sensor_evento_ins(
  p_sensor_id IN NUMBER, p_vaga_id IN NUMBER, p_ocorrido IN TIMESTAMP WITH TIME ZONE,
  p_status IN VARCHAR2, p_payload IN VARCHAR2, p_id OUT NUMBER
) IS
BEGIN
  INSERT INTO sensor_evento(sensor_id, vaga_id, ocorrido_em, recebido_em, status, payload)
  VALUES (p_sensor_id, p_vaga_id, p_ocorrido, SYSTIMESTAMP, p_status, p_payload)
  RETURNING id INTO p_id;
END;
/
CREATE OR REPLACE PROCEDURE sensor_evento_upd(
  p_id IN NUMBER, p_status IN VARCHAR2, p_payload IN VARCHAR2
) IS
BEGIN
  UPDATE sensor_evento SET status=p_status, payload=p_payload WHERE id=p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Sensor_evento não encontrado.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE sensor_evento_del(p_id IN NUMBER) IS
BEGIN
  DELETE FROM sensor_evento WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Sensor_evento não encontrado.'); END IF;
END;
/

-- USUARIO (usa fn_validar_email)
CREATE OR REPLACE PROCEDURE usuario_ins(
  p_nome IN VARCHAR2, p_email IN VARCHAR2, p_senha_hash IN VARCHAR2, p_tel IN VARCHAR2, p_perfil IN VARCHAR2, p_id OUT NUMBER
) IS
BEGIN
  IF fn_validar_email(p_email) = 0 THEN
    raise_application_error(-20001,'E-mail inválido.');
  END IF;
  INSERT INTO usuario(nome, email, senha_hash, telefone, perfil, suspenso, no_shows, criado_em)
  VALUES (p_nome, p_email, p_senha_hash, p_tel, p_perfil, 'N', 0, SYSTIMESTAMP)
  RETURNING id INTO p_id;
EXCEPTION WHEN DUP_VAL_ON_INDEX THEN
  raise_application_error(-20001,'E-mail já cadastrado.');
END;
/
CREATE OR REPLACE PROCEDURE usuario_upd(
  p_id IN NUMBER, p_nome IN VARCHAR2, p_email IN VARCHAR2, p_tel IN VARCHAR2, p_perfil IN VARCHAR2
) IS
BEGIN
  IF fn_validar_email(p_email) = 0 THEN
    raise_application_error(-20001,'E-mail inválido.');
  END IF;
  UPDATE usuario SET nome=p_nome, email=p_email, telefone=p_tel, perfil=p_perfil WHERE id=p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Usuário não encontrado.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE usuario_del(p_id IN NUMBER) IS
BEGIN
  DELETE FROM usuario WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Usuário não encontrado.'); END IF;
END;
/

-- RESERVA (usa fn_validar_antecedencia)
CREATE OR REPLACE PROCEDURE reserva_ins(
  p_usuario_id           IN NUMBER,
  p_vaga_id              IN NUMBER,
  p_inicio_previsto      IN TIMESTAMP WITH TIME ZONE,
  p_duracao_minutos      IN NUMBER,
  p_antecedencia_minutos IN NUMBER,
  p_id                   OUT NUMBER
) IS
  v_estac_id NUMBER;
  v_ok       NUMBER;
BEGIN
  -- Descobre o estacionamento da vaga
  SELECT n.estacionamento_id
    INTO v_estac_id
    FROM vaga v
    JOIN nivel n ON n.id = v.nivel_id
   WHERE v.id = p_vaga_id;

  -- Valida antecedência para este estacionamento/usuário
  v_ok := fn_validar_antecedencia(v_estac_id, p_usuario_id, p_antecedencia_minutos);
  IF v_ok = 0 THEN
    raise_application_error(-20001,'Antecedência inválida para este estacionamento/usuário.');
  END IF;

  -- Cria PRE_RESERVA
  INSERT INTO reserva(
      usuario_id, vaga_id, estado, criado_em,
      inicio_previsto, duracao_minutos, antecedencia_minutos,
      eta_origem, eta_minutos, eta_atualizado_em, vaga_bloqueada
  )
  VALUES (
      p_usuario_id, p_vaga_id, 'PRE_RESERVA', SYSTIMESTAMP,
      p_inicio_previsto, p_duracao_minutos, p_antecedencia_minutos,
      NULL, NULL, NULL, 'N'
  )
  RETURNING id INTO p_id;

  -- Histórico da criação (ATENÇÃO: use apenas as colunas que EXISTEM no seu DDL)
  INSERT INTO reserva_hist(
      reserva_id, from_estado, to_estado, origem_evento, referencia_id, observacao, ocorrido_em
  ) VALUES (
      p_id, NULL, 'PRE_RESERVA', 'MANUAL', NULL, 'criação', SYSTIMESTAMP
  );

EXCEPTION
  WHEN NO_DATA_FOUND THEN
    raise_application_error(-20001,'Vaga ou estacionamento inexistente.');
  WHEN OTHERS THEN
    raise_application_error(-20003,'Falha ao inserir reserva: '||SQLERRM);
END;
/

CREATE OR REPLACE PROCEDURE reserva_upd(
  p_id IN NUMBER,
  p_inicio_previsto IN TIMESTAMP WITH TIME ZONE,
  p_duracao_minutos IN NUMBER,
  p_antecedencia_minutos IN NUMBER
) IS
  v_user NUMBER; v_vaga NUMBER; v_estac NUMBER; v_ok NUMBER;
BEGIN
  SELECT usuario_id, vaga_id INTO v_user, v_vaga FROM reserva WHERE id = p_id FOR UPDATE;
  SELECT n.estacionamento_id INTO v_estac
    FROM vaga v JOIN nivel n ON n.id = v.nivel_id
   WHERE v.id = v_vaga;

  v_ok := fn_validar_antecedencia(v_estac, v_user, p_antecedencia_minutos);
  IF v_ok = 0 THEN
    raise_application_error(-20001,'Antecedência inválida para este estacionamento/usuário.');
  END IF;

  UPDATE reserva
     SET inicio_previsto = p_inicio_previsto,
         duracao_minutos = p_duracao_minutos,
         antecedencia_minutos = p_antecedencia_minutos
   WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Reserva não encontrada.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE reserva_del(p_id IN NUMBER) IS
  v_estado VARCHAR2(20);
BEGIN
  SELECT estado INTO v_estado FROM reserva WHERE id = p_id FOR UPDATE;
  IF v_estado IN ('OCUPADA','PAGA') THEN
    raise_application_error(-20003,'Não é permitido excluir reserva OCUPADA/PAGA.');
  END IF;
  DELETE FROM reserva WHERE id = p_id;
END;
/

-- RESERVA_PRECO (snapshot)
CREATE OR REPLACE PROCEDURE reserva_preco_ins(
  p_reserva_id IN NUMBER,
  p_tarifa IN NUMBER, p_perc_ant IN NUMBER, p_ant_aplicada IN NUMBER,
  p_obs IN VARCHAR2, p_val_prev IN NUMBER, p_val_final IN NUMBER, p_moeda IN VARCHAR2
) IS
BEGIN
  INSERT INTO reserva_preco(reserva_id, tarifa_por_minuto, percentual_antecedencia,
                            antecedencia_minutos_aplicada, observacao, valor_previsto, valor_final, moeda, calculado_em)
  VALUES (p_reserva_id, p_tarifa, p_perc_ant, p_ant_aplicada, p_obs, p_val_prev, p_val_final, p_moeda, SYSTIMESTAMP);
END;
/
CREATE OR REPLACE PROCEDURE reserva_preco_upd(
  p_reserva_id IN NUMBER, p_val_final IN NUMBER
) IS
BEGIN
  UPDATE reserva_preco SET valor_final = p_val_final WHERE reserva_id = p_reserva_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Reserva_preco não encontrada.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE reserva_preco_del(p_reserva_id IN NUMBER) IS
BEGIN
  DELETE FROM reserva_preco WHERE reserva_id = p_reserva_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Reserva_preco não encontrada.'); END IF;
END;
/

-- RESERVA_HIST (usado para auditoria)
CREATE OR REPLACE PROCEDURE reserva_hist_ins(
  p_reserva_id IN NUMBER, p_from IN VARCHAR2, p_to IN VARCHAR2, p_origem IN VARCHAR2,
  p_ref_id IN NUMBER, p_obs IN VARCHAR2
) IS
BEGIN
  INSERT INTO reserva_hist(reserva_id, from_estado, to_estado, origem_evento, referencia_id, observacao, ocorrido_em)
  VALUES (p_reserva_id, p_from, p_to, p_origem, p_ref_id, p_obs, SYSTIMESTAMP);
END;
/
CREATE OR REPLACE PROCEDURE reserva_hist_del(p_id IN NUMBER) IS
BEGIN
  DELETE FROM reserva_hist WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Reserva_hist não encontrada.'); END IF;
END;
/

-- PAGAMENTO (usa chave de idempotência)
CREATE OR REPLACE PROCEDURE pagamento_ins(
  p_reserva_id IN NUMBER,
  p_valor IN NUMBER,
  p_metodo IN VARCHAR2,
  p_idempotencia IN VARCHAR2,
  p_gateway_provider IN VARCHAR2,
  p_gateway_tx_id IN VARCHAR2,
  p_gateway_response IN VARCHAR2,
  p_id OUT NUMBER
) IS
BEGIN
  INSERT INTO pagamento(reserva_id, valor, status, criado_em, metodo_pagamento,
                        idempotencia_chave, gateway_provider, gateway_tx_id, gateway_response)
  VALUES (p_reserva_id, p_valor, 'PENDING', SYSTIMESTAMP, p_metodo,
          p_idempotencia, p_gateway_provider, p_gateway_tx_id, p_gateway_response)
  RETURNING id INTO p_id;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    raise_application_error(-20001,'Chave de idempotência já utilizada.');
  WHEN OTHERS THEN
    raise_application_error(-20003,'Falha ao inserir pagamento: '||SQLERRM);
END;
/
CREATE OR REPLACE PROCEDURE pagamento_upd_status(
  p_id IN NUMBER, p_status IN VARCHAR2
) IS
BEGIN
  UPDATE pagamento SET status = p_status WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Pagamento não encontrado.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE pagamento_del(p_id IN NUMBER) IS
BEGIN
  DELETE FROM pagamento WHERE id = p_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Pagamento não encontrado.'); END IF;
END;
/

-- PAGAMENTO_PAGADOR (usa validações cpf_cnpj e e-mail)
CREATE OR REPLACE PROCEDURE pagamento_pagador_ins(
  p_pagamento_id IN NUMBER, p_nome IN VARCHAR2, p_cpf_cnpj IN VARCHAR2, p_email IN VARCHAR2,
  p_telefone IN VARCHAR2, p_endereco_id IN NUMBER
) IS
BEGIN
  IF fn_validar_cpf_cnpj(p_cpf_cnpj) = 0 THEN
    raise_application_error(-20001,'CPF/CNPJ inválido.');
  END IF;
  IF fn_validar_email(p_email) = 0 THEN
    raise_application_error(-20001,'E-mail inválido.');
  END IF;
  INSERT INTO pagamento_pagador(pagamento_id, nome, cpf_cnpj, email, telefone, endereco_id)
  VALUES (p_pagamento_id, p_nome, p_cpf_cnpj, p_email, p_telefone, p_endereco_id);
END;
/
CREATE OR REPLACE PROCEDURE pagamento_pagador_upd(
  p_pagamento_id IN NUMBER, p_nome IN VARCHAR2, p_cpf_cnpj IN VARCHAR2, p_email IN VARCHAR2,
  p_telefone IN VARCHAR2, p_endereco_id IN NUMBER
) IS
BEGIN
  IF fn_validar_cpf_cnpj(p_cpf_cnpj) = 0 THEN raise_application_error(-20001,'CPF/CNPJ inválido.'); END IF;
  IF fn_validar_email(p_email) = 0 THEN raise_application_error(-20001,'E-mail inválido.'); END IF;
  UPDATE pagamento_pagador
     SET nome=p_nome, cpf_cnpj=p_cpf_cnpj, email=p_email, telefone=p_telefone, endereco_id=p_endereco_id
   WHERE pagamento_id = p_pagamento_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Pagador não encontrado.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE pagamento_pagador_del(p_pagamento_id IN NUMBER) IS
BEGIN
  DELETE FROM pagamento_pagador WHERE pagamento_id = p_pagamento_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Pagador não encontrado.'); END IF;
END;
/

-- PAGAMENTO_CARTAO
CREATE OR REPLACE PROCEDURE pagamento_cartao_ins(
  p_pagamento_id IN NUMBER, p_token IN VARCHAR2, p_bandeira IN VARCHAR2, p_final IN VARCHAR2, p_titular IN VARCHAR2
) IS
BEGIN
  INSERT INTO pagamento_cartao(pagamento_id, token, bandeira, final_cartao, titular_nome)
  VALUES (p_pagamento_id, p_token, p_bandeira, p_final, p_titular);
END;
/
CREATE OR REPLACE PROCEDURE pagamento_cartao_upd(
  p_pagamento_id IN NUMBER, p_token IN VARCHAR2, p_bandeira IN VARCHAR2, p_final IN VARCHAR2, p_titular IN VARCHAR2
) IS
BEGIN
  UPDATE pagamento_cartao
     SET token=p_token, bandeira=p_bandeira, final_cartao=p_final, titular_nome=p_titular
   WHERE pagamento_id = p_pagamento_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Pagamento_cartao não encontrado.'); END IF;
END;
/
CREATE OR REPLACE PROCEDURE pagamento_cartao_del(p_pagamento_id IN NUMBER) IS
BEGIN
  DELETE FROM pagamento_cartao WHERE pagamento_id = p_pagamento_id;
  IF SQL%ROWCOUNT = 0 THEN raise_application_error(-20002,'Pagamento_cartao não encontrado.'); END IF;
END;
/

--------------------------------------------------------------------------------
-- ITEM 5: Função com cursor + JOINs para relatório
-- Saída: tabela com reservas e contexto (usuario, vaga, estacionamento)
--------------------------------------------------------------------------------

-- Tipos SQL
CREATE OR REPLACE TYPE t_rel_reserva_row AS OBJECT (
  reserva_id        NUMBER,
  usuario_email     VARCHAR2(320),
  estacionamento    VARCHAR2(250),
  vaga_codigo       VARCHAR2(50),
  estado            VARCHAR2(20),
  criado_em         TIMESTAMP WITH TIME ZONE
);
/
CREATE OR REPLACE TYPE t_rel_reserva_tab AS TABLE OF t_rel_reserva_row;
/

-- Função que retorna a tabela 
CREATE OR REPLACE FUNCTION fn_rel_reservas(
  p_ini IN TIMESTAMP WITH TIME ZONE,
  p_fim IN TIMESTAMP WITH TIME ZONE
) RETURN t_rel_reserva_tab IS
  v_res t_rel_reserva_tab := t_rel_reserva_tab();
  CURSOR c IS
    SELECT r.id, u.email, e.nome, v.codigo, r.estado, r.criado_em
      FROM reserva r
      JOIN usuario u       ON u.id = r.usuario_id
      JOIN vaga v          ON v.id = r.vaga_id
      JOIN nivel n         ON n.id = v.nivel_id
      JOIN estacionamento e ON e.id = n.estacionamento_id
     WHERE r.criado_em BETWEEN p_ini AND p_fim
     ORDER BY r.criado_em DESC, e.nome, v.codigo;
  v_row c%ROWTYPE;
BEGIN
  FOR v_row IN c LOOP
    v_res.EXTEND;
    v_res(v_res.LAST) := t_rel_reserva_row(
      v_row.id, v_row.email, v_row.nome, v_row.codigo, v_row.estado, v_row.criado_em
    );
  END LOOP;
  RETURN v_res;
END;
/
SHOW ERRORS

-- Exemplo de uso:
-- SELECT * FROM TABLE(fn_rel_reservas(SYSTIMESTAMP-INTERVAL '7' DAY, SYSTIMESTAMP));

--------------------------------------------------------------------------------
-- ITEM 6: Função com regra de negócio + INNER JOIN + ORDER BY + agregações
-- Regra: faturamento por dia/estacionamento para pagamentos com status 'SUCCEEDED'
--------------------------------------------------------------------------------

CREATE OR REPLACE TYPE t_fat_row AS OBJECT (
  dia              DATE,
  estacionamento   VARCHAR2(250),
  qtd_transacoes   NUMBER,
  valor_total      NUMBER(12,2)
);
/
CREATE OR REPLACE TYPE t_fat_tab AS TABLE OF t_fat_row;
/

CREATE OR REPLACE FUNCTION fn_rel_faturamento(
  p_ini IN DATE,
  p_fim IN DATE
) RETURN t_fat_tab IS
  v_res t_fat_tab := t_fat_tab();
  CURSOR c IS
    SELECT TRUNC(p.criado_em) AS dia, e.nome AS estacionamento,
           COUNT(*) AS qtd, SUM(p.valor) AS total
      FROM pagamento p
      INNER JOIN reserva r       ON r.id = p.reserva_id
      INNER JOIN vaga v          ON v.id = r.vaga_id
      INNER JOIN nivel n         ON n.id = v.nivel_id
      INNER JOIN estacionamento e ON e.id = n.estacionamento_id
     WHERE p.status = 'SUCCEEDED'
       AND TRUNC(p.criado_em) BETWEEN p_ini AND p_fim
     GROUP BY TRUNC(p.criado_em), e.nome
     ORDER BY dia DESC, estacionamento;
  v_row c%ROWTYPE;
BEGIN
  FOR v_row IN c LOOP
    v_res.EXTEND;
    v_res(v_res.LAST) := t_fat_row(v_row.dia, v_row.estacionamento, v_row.qtd, NVL(v_row.total,0));
  END LOOP;
  RETURN v_res;
END;
/
SHOW ERRORS

-- Exemplo de uso:
-- SELECT * FROM TABLE(fn_rel_faturamento(TRUNC(SYSDATE)-7, TRUNC(SYSDATE)));
