-- ============================================================================
-- EASYPARK - SPRINT 3
-- ============================================================================

SET SERVEROUTPUT ON SIZE UNLIMITED;

-- ----------------------------------------------------------------------------
-- LIMPEZA INICIAL
-- Remove objetos, se já existirem.
-- ----------------------------------------------------------------------------
PROMPT ========================================
PROMPT INICIANDO LIMPEZA DE OBJETOS DA SPRINT 3
PROMPT ========================================

BEGIN
  EXECUTE IMMEDIATE 'DROP TRIGGER trg_s3_auditoria_reserva';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -4080 THEN
      RAISE;
    END IF;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE auditoria_reserva_s3 PURGE';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN
      RAISE;
    END IF;
END;
/

-- ============================================================================
-- FASE 1 - IMPLEMENTAÇÃO
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TABELA DE AUDITORIA
-- Armazena o histórico das operações INSERT, UPDATE e DELETE feitas na tabela
-- RESERVA, incluindo usuário do banco, data e retrato OLD/NEW da linha.
-- ----------------------------------------------------------------------------
PROMPT ========================================
PROMPT CRIANDO TABELA DE AUDITORIA
PROMPT ========================================

CREATE TABLE auditoria_reserva_s3 (
  id               NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reserva_id       NUMBER,
  nome_tabela      VARCHAR2(50)   DEFAULT 'RESERVA' NOT NULL,
  operacao         VARCHAR2(10)   NOT NULL,
  usuario_banco    VARCHAR2(128)  NOT NULL,
  data_operacao    TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL,
  dados_old        CLOB,
  dados_new        CLOB,
  CONSTRAINT chk_auditoria_reserva_s3_operacao
    CHECK (operacao IN ('INSERT','UPDATE','DELETE'))
);

-- ----------------------------------------------------------------------------
-- FUNÇÃO 1: JSON MANUAL
-- Converte o contexto de uma reserva em um JSON montado manualmente
-- ----------------------------------------------------------------------------
PROMPT ========================================
PROMPT CRIANDO FUNCAO 1 - JSON MANUAL
PROMPT ========================================

CREATE OR REPLACE FUNCTION fn_s3_json_reserva_contexto(
  p_reserva_id            IN NUMBER,
  p_usuario_nome          IN VARCHAR2,
  p_usuario_email         IN VARCHAR2,
  p_estacionamento_nome   IN VARCHAR2,
  p_nivel_nome            IN VARCHAR2,
  p_vaga_codigo           IN VARCHAR2,
  p_estado                IN VARCHAR2,
  p_inicio_previsto       IN TIMESTAMP WITH TIME ZONE,
  p_duracao_minutos       IN NUMBER,
  p_antecedencia_minutos  IN NUMBER,
  p_valor_previsto        IN NUMBER,
  p_valor_final           IN NUMBER
) RETURN CLOB IS
  v_json CLOB;

  FUNCTION esc(p_texto IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN REPLACE(
             REPLACE(
               REPLACE(
                 REPLACE(NVL(p_texto, ''), '\\', '\\\\'),
               '"', '\\"'),
             CHR(10), '\\n'),
           CHR(13), '\\r');
  END;

  FUNCTION txt(p_texto IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    IF p_texto IS NULL THEN
      RETURN 'null';
    END IF;
    RETURN '"' || esc(p_texto) || '"';
  END;

  FUNCTION num(p_numero IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    IF p_numero IS NULL THEN
      RETURN 'null';
    END IF;
    RETURN TO_CHAR(p_numero, 'FM9999999999999990D9999', 'NLS_NUMERIC_CHARACTERS = '',.''');
  EXCEPTION
    WHEN OTHERS THEN
      RETURN TO_CHAR(p_numero);
  END;

  FUNCTION ts(p_data IN TIMESTAMP WITH TIME ZONE) RETURN VARCHAR2 IS
  BEGIN
    IF p_data IS NULL THEN
      RETURN 'null';
    END IF;
    RETURN '"' || TO_CHAR(p_data, 'YYYY-MM-DD"T"HH24:MI:SS TZH:TZM') || '"';
  END;

BEGIN
  IF p_reserva_id IS NULL THEN
    RAISE VALUE_ERROR;
  END IF;

  IF p_reserva_id <= 0 THEN
    RAISE NO_DATA_FOUND;
  END IF;

  IF NVL(p_duracao_minutos, 0) < 0 OR NVL(p_antecedencia_minutos, 0) < 0 THEN
    RAISE VALUE_ERROR;
  END IF;

  v_json := '{'
         || '"reservaId":'            || num(p_reserva_id)
         || ',"usuarioNome":'         || txt(p_usuario_nome)
         || ',"usuarioEmail":'        || txt(p_usuario_email)
         || ',"estacionamento":'      || txt(p_estacionamento_nome)
         || ',"nivel":'               || txt(p_nivel_nome)
         || ',"vagaCodigo":'          || txt(p_vaga_codigo)
         || ',"estado":'              || txt(p_estado)
         || ',"inicioPrevisto":'      || ts(p_inicio_previsto)
         || ',"duracaoMinutos":'      || num(p_duracao_minutos)
         || ',"antecedenciaMinutos":' || num(p_antecedencia_minutos)
         || ',"valorPrevisto":'       || num(p_valor_previsto)
         || ',"valorFinal":'          || num(p_valor_final)
         || '}';

  RETURN v_json;

EXCEPTION
  WHEN VALUE_ERROR THEN
    RETURN '{"erro":"Parametros invalidos para gerar JSON da reserva."}';
  WHEN NO_DATA_FOUND THEN
    RETURN '{"erro":"Reserva nao localizada para gerar JSON."}';
  WHEN OTHERS THEN
    RETURN '{"erro":"Falha inesperada ao gerar JSON da reserva: ' || esc(SQLERRM) || '"}';
END;
/
SHOW ERRORS

-- ----------------------------------------------------------------------------
-- FUNÇÃO 2: REGRA DE NEGÓCIO
-- Calcula o valor previsto de uma reserva com base na vaga, duração e
-- antecedência, reaproveitando a tarifa do tipo de vaga cadastrada no projeto.
-- ----------------------------------------------------------------------------
PROMPT ========================================
PROMPT CRIANDO FUNCAO 2 - REGRA DE NEGOCIO
PROMPT ========================================

CREATE OR REPLACE FUNCTION fn_s3_calcular_valor_previsto(
  p_vaga_id               IN NUMBER,
  p_duracao_minutos       IN NUMBER,
  p_antecedencia_minutos  IN NUMBER
) RETURN NUMBER IS
  v_tarifa_por_minuto     tipo_vaga.tarifa_por_minuto%TYPE;
  v_fator_antecedencia    NUMBER(12,6);
  v_valor                 NUMBER(12,4);
  e_duracao_excessiva     EXCEPTION;
BEGIN
  IF p_vaga_id IS NULL OR p_duracao_minutos IS NULL OR p_antecedencia_minutos IS NULL THEN
    RAISE VALUE_ERROR;
  END IF;

  IF p_duracao_minutos <= 0 OR p_antecedencia_minutos < 0 THEN
    RAISE VALUE_ERROR;
  END IF;

  IF p_duracao_minutos > 1440 THEN
    RAISE e_duracao_excessiva;
  END IF;

  SELECT tv.tarifa_por_minuto
    INTO v_tarifa_por_minuto
    FROM vaga v
    JOIN tipo_vaga tv
      ON tv.id = v.tipo_vaga_id
   WHERE v.id = p_vaga_id;

  -- percentual de antecedência aplicado sobre a duração.
  v_fator_antecedencia := 1 + (p_antecedencia_minutos * 0.01);
  v_valor := ROUND(v_tarifa_por_minuto * p_duracao_minutos * v_fator_antecedencia, 4);

  RETURN v_valor;

EXCEPTION
  WHEN VALUE_ERROR THEN
    RAISE_APPLICATION_ERROR(-20301, 'Parametros invalidos para calculo do valor previsto.');
  WHEN NO_DATA_FOUND THEN
    RAISE_APPLICATION_ERROR(-20302, 'Vaga nao encontrada para calculo do valor previsto.');
  WHEN e_duracao_excessiva THEN
    RAISE_APPLICATION_ERROR(-20303, 'Duracao acima do limite permitido para o calculo (1440 minutos).');
END;
/
SHOW ERRORS

-- ----------------------------------------------------------------------------
-- PROCEDURE 1: JOIN + JSON
-- Gera um relatório de reservas combinando várias tabelas do domínio 
-- e transforma cada linha em JSON com a função criada.
-- ----------------------------------------------------------------------------
PROMPT ========================================
PROMPT CRIANDO PROCEDURE 1 - JOIN + JSON
PROMPT ========================================

CREATE OR REPLACE PROCEDURE prc_s3_rel_reservas_json(
  p_estado     IN VARCHAR2 DEFAULT NULL,
  p_max_linhas IN NUMBER   DEFAULT 10
) IS
  v_json        CLOB;
  v_total       NUMBER;
  v_estado      VARCHAR2(20);
  v_emitidas    NUMBER := 0;
BEGIN
  IF p_max_linhas IS NULL OR p_max_linhas <= 0 THEN
    RAISE VALUE_ERROR;
  END IF;

  v_estado := UPPER(TRIM(p_estado));

  IF v_estado IS NOT NULL
     AND v_estado NOT IN ('PRE_RESERVA','RESERVA','OCUPADA','PAGA','CANCELADA','EXPIRED') THEN
    RAISE VALUE_ERROR;
  END IF;

  SELECT COUNT(*)
    INTO v_total
    FROM reserva r
    JOIN usuario u
      ON u.id = r.usuario_id
    JOIN vaga v
      ON v.id = r.vaga_id
    JOIN nivel n
      ON n.id = v.nivel_id
    JOIN estacionamento e
      ON e.id = n.estacionamento_id
    LEFT JOIN reserva_preco rp
      ON rp.reserva_id = r.id
   WHERE v_estado IS NULL OR r.estado = v_estado;

  IF v_total = 0 THEN
    RAISE NO_DATA_FOUND;
  END IF;

  DBMS_OUTPUT.PUT_LINE('===== RELATORIO JSON DE RESERVAS =====');
  DBMS_OUTPUT.PUT_LINE('Filtro estado: ' || NVL(v_estado, 'TODOS'));
  DBMS_OUTPUT.PUT_LINE('Quantidade encontrada: ' || v_total);
  DBMS_OUTPUT.PUT_LINE('--------------------------------------');

  FOR rec IN (
    SELECT r.id,
           u.nome AS usuario_nome,
           u.email AS usuario_email,
           e.nome AS estacionamento_nome,
           n.nome AS nivel_nome,
           v.codigo AS vaga_codigo,
           r.estado,
           r.inicio_previsto,
           r.duracao_minutos,
           r.antecedencia_minutos,
           rp.valor_previsto,
           rp.valor_final
      FROM reserva r
      JOIN usuario u
        ON u.id = r.usuario_id
      JOIN vaga v
        ON v.id = r.vaga_id
      JOIN nivel n
        ON n.id = v.nivel_id
      JOIN estacionamento e
        ON e.id = n.estacionamento_id
      LEFT JOIN reserva_preco rp
        ON rp.reserva_id = r.id
     WHERE v_estado IS NULL OR r.estado = v_estado
     ORDER BY r.id
  ) LOOP
    EXIT WHEN v_emitidas >= p_max_linhas;

    v_json := fn_s3_json_reserva_contexto(
                rec.id,
                rec.usuario_nome,
                rec.usuario_email,
                rec.estacionamento_nome,
                rec.nivel_nome,
                rec.vaga_codigo,
                rec.estado,
                rec.inicio_previsto,
                rec.duracao_minutos,
                rec.antecedencia_minutos,
                rec.valor_previsto,
                rec.valor_final
              );

    DBMS_OUTPUT.PUT_LINE(DBMS_LOB.SUBSTR(v_json, 32767, 1));
    v_emitidas := v_emitidas + 1;
  END LOOP;

  DBMS_OUTPUT.PUT_LINE('--------------------------------------');
  DBMS_OUTPUT.PUT_LINE('Total emitido: ' || v_emitidas);

EXCEPTION
  WHEN VALUE_ERROR THEN
    DBMS_OUTPUT.PUT_LINE('ERRO: parametros invalidos. Informe um estado valido e p_max_linhas maior que zero.');
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('ERRO: nao ha reservas para o filtro informado.');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERRO inesperado ao gerar relatorio JSON: ' || SQLERRM);
END;
/
SHOW ERRORS

-- ----------------------------------------------------------------------------
-- PROCEDURE 2: ANTERIOR / ATUAL / PRÓXIMO
-- Lê a tabela PAGAMENTO e mostra, para a coluna VALOR, o valor anterior, atual
-- e próximo em cada linha, exibindo "Vazio" quando não houver vizinho.
-- ----------------------------------------------------------------------------
PROMPT ========================================
PROMPT CRIANDO PROCEDURE 2 - ANTERIOR / ATUAL / PROXIMO
PROMPT ========================================

CREATE OR REPLACE PROCEDURE prc_s3_rel_pagamentos_vizinhos(
  p_min_linhas IN NUMBER DEFAULT 5
) IS
  v_total NUMBER;
BEGIN
  IF p_min_linhas IS NULL OR p_min_linhas <= 0 THEN
    RAISE VALUE_ERROR;
  END IF;

  SELECT COUNT(*)
    INTO v_total
    FROM pagamento;

  IF v_total < p_min_linhas THEN
    RAISE NO_DATA_FOUND;
  END IF;

  DBMS_OUTPUT.PUT_LINE('===== RELATORIO PAGAMENTOS (ANTERIOR / ATUAL / PROXIMO) =====');
  DBMS_OUTPUT.PUT_LINE(RPAD('ID_PGTO', 12)
                    || RPAD('ID_USUARIO', 12)
                    || RPAD('ANTERIOR', 18)
                    || RPAD('ATUAL', 18)
                    || RPAD('PROXIMO', 18));
  DBMS_OUTPUT.PUT_LINE(RPAD('-', 78, '-'));

  FOR rec IN (
    SELECT id,
           usuario_id,
           NVL(TO_CHAR(LAG(valor) OVER (ORDER BY id), 'FM9999990D0000', 'NLS_NUMERIC_CHARACTERS = '',.'''), 'Vazio') AS anterior,
           TO_CHAR(valor, 'FM9999990D0000', 'NLS_NUMERIC_CHARACTERS = '',.''') AS atual,
           NVL(TO_CHAR(LEAD(valor) OVER (ORDER BY id), 'FM9999990D0000', 'NLS_NUMERIC_CHARACTERS = '',.'''), 'Vazio') AS proximo
      FROM pagamento
     ORDER BY id
  ) LOOP
    DBMS_OUTPUT.PUT_LINE(RPAD(TO_CHAR(rec.id), 12)
                      || RPAD(NVL(TO_CHAR(rec.usuario_id), 'Vazio'), 12)
                      || RPAD(rec.anterior, 18)
                      || RPAD(rec.atual, 18)
                      || RPAD(rec.proximo, 18));
  END LOOP;

EXCEPTION
  WHEN VALUE_ERROR THEN
    DBMS_OUTPUT.PUT_LINE('ERRO: p_min_linhas deve ser maior que zero.');
  WHEN NO_DATA_FOUND THEN
    DBMS_OUTPUT.PUT_LINE('ERRO: a tabela PAGAMENTO nao possui a quantidade minima de linhas para o relatorio.');
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('ERRO inesperado ao gerar relatorio de pagamentos: ' || SQLERRM);
END;
/
SHOW ERRORS

-- ----------------------------------------------------------------------------
-- TRIGGER DE AUDITORIA
-- Monitora INSERT, UPDATE e DELETE na tabela RESERVA e grava automaticamente
-- a operação na tabela AUDITORIA_RESERVA_S3.
-- ----------------------------------------------------------------------------
PROMPT ========================================
PROMPT CRIANDO TRIGGER DE AUDITORIA
PROMPT ========================================

CREATE OR REPLACE TRIGGER trg_s3_auditoria_reserva
AFTER INSERT OR UPDATE OR DELETE ON reserva
FOR EACH ROW
DECLARE
  v_old_json CLOB;
  v_new_json CLOB;

  FUNCTION esc(p_texto IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN REPLACE(
             REPLACE(
               REPLACE(
                 REPLACE(NVL(p_texto, ''), '\\', '\\\\'),
               '"', '\\"'),
             CHR(10), '\\n'),
           CHR(13), '\\r');
  END;

  FUNCTION txt(p_texto IN VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    IF p_texto IS NULL THEN
      RETURN 'null';
    END IF;
    RETURN '"' || esc(p_texto) || '"';
  END;

  FUNCTION num(p_numero IN NUMBER) RETURN VARCHAR2 IS
  BEGIN
    IF p_numero IS NULL THEN
      RETURN 'null';
    END IF;
    RETURN TO_CHAR(p_numero, 'FM9999999999999990D9999', 'NLS_NUMERIC_CHARACTERS = '',.''');
  END;

  FUNCTION ts(p_data IN TIMESTAMP WITH TIME ZONE) RETURN VARCHAR2 IS
  BEGIN
    IF p_data IS NULL THEN
      RETURN 'null';
    END IF;
    RETURN '"' || TO_CHAR(p_data, 'YYYY-MM-DD"T"HH24:MI:SS TZH:TZM') || '"';
  END;

  FUNCTION json_reserva(
    p_id                   IN NUMBER,
    p_usuario_id           IN NUMBER,
    p_vaga_id              IN NUMBER,
    p_estado               IN VARCHAR2,
    p_criado_em            IN TIMESTAMP WITH TIME ZONE,
    p_inicio_previsto      IN TIMESTAMP WITH TIME ZONE,
    p_duracao_minutos      IN NUMBER,
    p_antecedencia_minutos IN NUMBER,
    p_confirmado_em        IN TIMESTAMP WITH TIME ZONE,
    p_ocupado_em           IN TIMESTAMP WITH TIME ZONE,
    p_pago_em              IN TIMESTAMP WITH TIME ZONE,
    p_motivo_cancelamento  IN VARCHAR2,
    p_vaga_bloqueada       IN CHAR,
    p_eta_origem           IN VARCHAR2,
    p_eta_minutos          IN NUMBER,
    p_eta_atualizado_em    IN TIMESTAMP WITH TIME ZONE
  ) RETURN CLOB IS
    v_json CLOB;
  BEGIN
    v_json := '{'
           || '"id":'                   || num(p_id)
           || ',"usuarioId":'          || num(p_usuario_id)
           || ',"vagaId":'             || num(p_vaga_id)
           || ',"estado":'             || txt(p_estado)
           || ',"criadoEm":'           || ts(p_criado_em)
           || ',"inicioPrevisto":'     || ts(p_inicio_previsto)
           || ',"duracaoMinutos":'     || num(p_duracao_minutos)
           || ',"antecedenciaMinutos":'|| num(p_antecedencia_minutos)
           || ',"confirmadoEm":'       || ts(p_confirmado_em)
           || ',"ocupadoEm":'          || ts(p_ocupado_em)
           || ',"pagoEm":'             || ts(p_pago_em)
           || ',"motivoCancelamento":' || txt(p_motivo_cancelamento)
           || ',"vagaBloqueada":'      || txt(p_vaga_bloqueada)
           || ',"etaOrigem":'          || txt(p_eta_origem)
           || ',"etaMinutos":'         || num(p_eta_minutos)
           || ',"etaAtualizadoEm":'    || ts(p_eta_atualizado_em)
           || '}';
    RETURN v_json;
  END;
BEGIN
  IF INSERTING THEN
    v_new_json := json_reserva(
                    :NEW.id,
                    :NEW.usuario_id,
                    :NEW.vaga_id,
                    :NEW.estado,
                    :NEW.criado_em,
                    :NEW.inicio_previsto,
                    :NEW.duracao_minutos,
                    :NEW.antecedencia_minutos,
                    :NEW.confirmado_em,
                    :NEW.ocupado_em,
                    :NEW.pago_em,
                    :NEW.motivo_cancelamento,
                    :NEW.vaga_bloqueada,
                    :NEW.eta_origem,
                    :NEW.eta_minutos,
                    :NEW.eta_atualizado_em
                  );

    INSERT INTO auditoria_reserva_s3(
      reserva_id, operacao, usuario_banco, data_operacao, dados_old, dados_new
    ) VALUES (
      :NEW.id,
      'INSERT',
      SYS_CONTEXT('USERENV', 'SESSION_USER'),
      SYSTIMESTAMP,
      NULL,
      v_new_json
    );

  ELSIF UPDATING THEN
    v_old_json := json_reserva(
                    :OLD.id,
                    :OLD.usuario_id,
                    :OLD.vaga_id,
                    :OLD.estado,
                    :OLD.criado_em,
                    :OLD.inicio_previsto,
                    :OLD.duracao_minutos,
                    :OLD.antecedencia_minutos,
                    :OLD.confirmado_em,
                    :OLD.ocupado_em,
                    :OLD.pago_em,
                    :OLD.motivo_cancelamento,
                    :OLD.vaga_bloqueada,
                    :OLD.eta_origem,
                    :OLD.eta_minutos,
                    :OLD.eta_atualizado_em
                  );

    v_new_json := json_reserva(
                    :NEW.id,
                    :NEW.usuario_id,
                    :NEW.vaga_id,
                    :NEW.estado,
                    :NEW.criado_em,
                    :NEW.inicio_previsto,
                    :NEW.duracao_minutos,
                    :NEW.antecedencia_minutos,
                    :NEW.confirmado_em,
                    :NEW.ocupado_em,
                    :NEW.pago_em,
                    :NEW.motivo_cancelamento,
                    :NEW.vaga_bloqueada,
                    :NEW.eta_origem,
                    :NEW.eta_minutos,
                    :NEW.eta_atualizado_em
                  );

    INSERT INTO auditoria_reserva_s3(
      reserva_id, operacao, usuario_banco, data_operacao, dados_old, dados_new
    ) VALUES (
      :NEW.id,
      'UPDATE',
      SYS_CONTEXT('USERENV', 'SESSION_USER'),
      SYSTIMESTAMP,
      v_old_json,
      v_new_json
    );

  ELSIF DELETING THEN
    v_old_json := json_reserva(
                    :OLD.id,
                    :OLD.usuario_id,
                    :OLD.vaga_id,
                    :OLD.estado,
                    :OLD.criado_em,
                    :OLD.inicio_previsto,
                    :OLD.duracao_minutos,
                    :OLD.antecedencia_minutos,
                    :OLD.confirmado_em,
                    :OLD.ocupado_em,
                    :OLD.pago_em,
                    :OLD.motivo_cancelamento,
                    :OLD.vaga_bloqueada,
                    :OLD.eta_origem,
                    :OLD.eta_minutos,
                    :OLD.eta_atualizado_em
                  );

    INSERT INTO auditoria_reserva_s3(
      reserva_id, operacao, usuario_banco, data_operacao, dados_old, dados_new
    ) VALUES (
      :OLD.id,
      'DELETE',
      SYS_CONTEXT('USERENV', 'SESSION_USER'),
      SYSTIMESTAMP,
      v_old_json,
      NULL
    );
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20390, 'Falha no trigger de auditoria da reserva: ' || SQLERRM);
END;
/
SHOW ERRORS

-- ============================================================================
-- FASE 2 - TESTES
-- ============================================================================
--  > 1 Testar a função JSON isoladamente.
--  > 2 Testar a função de negócio de cálculo.
--  > 3 Executar o Procedure 1 (join + JSON).
--  > 4 Executar o Procedure 2 (anterior / atual / próximo).
--  > 5 Testar o trigger de auditoria com INSERT / UPDATE / DELETE.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- TESTE 1
-- Executa a função JSON isoladamente para provar que uma reserva pode ser
-- transformada em saída no formato JSON.
-- ----------------------------------------------------------------------------
PROMPT ========================================
PROMPT TESTE 1 - FUNCAO JSON MANUAL
PROMPT ========================================

DECLARE
  v_json CLOB;
BEGIN
  SELECT fn_s3_json_reserva_contexto(
           r.id,
           u.nome,
           u.email,
           e.nome,
           n.nome,
           v.codigo,
           r.estado,
           r.inicio_previsto,
           r.duracao_minutos,
           r.antecedencia_minutos,
           rp.valor_previsto,
           rp.valor_final
         )
    INTO v_json
    FROM reserva r
    JOIN usuario u
      ON u.id = r.usuario_id
    JOIN vaga v
      ON v.id = r.vaga_id
    JOIN nivel n
      ON n.id = v.nivel_id
    JOIN estacionamento e
      ON e.id = n.estacionamento_id
    LEFT JOIN reserva_preco rp
      ON rp.reserva_id = r.id
   WHERE ROWNUM = 1;

  DBMS_OUTPUT.PUT_LINE(DBMS_LOB.SUBSTR(v_json, 32767, 1));
END;
/

-- ----------------------------------------------------------------------------
-- TESTE 2
-- Executa a função de cálculo do valor previsto usando uma vaga real da base
-- para validar a regra de negócio do banco.
-- ----------------------------------------------------------------------------
PROMPT ========================================
PROMPT TESTE 2 - FUNCAO DE REGRA DE NEGOCIO
PROMPT ========================================

DECLARE
  v_vaga_id NUMBER;
  v_valor   NUMBER;
BEGIN
  SELECT MIN(id)
    INTO v_vaga_id
    FROM vaga;

  v_valor := fn_s3_calcular_valor_previsto(v_vaga_id, 90, 30);

  DBMS_OUTPUT.PUT_LINE('Vaga utilizada no teste: ' || v_vaga_id);
  DBMS_OUTPUT.PUT_LINE('Valor previsto calculado para 90 minutos e 30 minutos de antecedencia: ' || TO_CHAR(v_valor));
END;
/

-- ----------------------------------------------------------------------------
-- TESTE 3
-- Executa o relatório de reservas com JOIN entre tabelas e saída em JSON,
-- validando o principal procedimento de transformação relacional -> JSON.
-- ----------------------------------------------------------------------------
PROMPT ========================================
PROMPT TESTE 3 - PROCEDURE 1 (JOIN + JSON)
PROMPT ========================================

BEGIN
  prc_s3_rel_reservas_json(NULL, 5);
END;
/

-- ----------------------------------------------------------------------------
-- TESTE 4
-- Executa o relatório sequencial da tabela PAGAMENTO, demonstrando os valores
-- anterior, atual e próximo com o comportamento esperado de borda.
-- ----------------------------------------------------------------------------
PROMPT ========================================
PROMPT TESTE 4 - PROCEDURE 2 (ANTERIOR / ATUAL / PROXIMO)
PROMPT ========================================

BEGIN
  prc_s3_rel_pagamentos_vizinhos(5);
END;
/

-- ----------------------------------------------------------------------------
-- TESTE 5
-- Cria, altera e remove uma reserva de teste para comprovar que o trigger gera
-- registros de auditoria para INSERT, UPDATE e DELETE.
-- ----------------------------------------------------------------------------
PROMPT ========================================
PROMPT TESTE 5 - TRIGGER DE AUDITORIA (INSERT / UPDATE / DELETE)
PROMPT ========================================

DECLARE
  v_usuario_id   NUMBER;
  v_vaga_id      NUMBER;
  v_reserva_id   NUMBER;
BEGIN
  SELECT MIN(id)
    INTO v_usuario_id
    FROM usuario;

  SELECT MIN(id)
    INTO v_vaga_id
    FROM vaga;

  INSERT INTO reserva(
    usuario_id,
    vaga_id,
    estado,
    criado_em,
    inicio_previsto,
    duracao_minutos,
    antecedencia_minutos,
    motivo_cancelamento,
    vaga_bloqueada,
    eta_origem,
    eta_minutos,
    eta_atualizado_em
  ) VALUES (
    v_usuario_id,
    v_vaga_id,
    'CANCELADA',
    SYSTIMESTAMP,
    SYSTIMESTAMP + INTERVAL '2' HOUR,
    45,
    10,
    'Registro de teste da auditoria Sprint 3',
    'N',
    NULL,
    NULL,
    NULL
  )
  RETURNING id INTO v_reserva_id;

  UPDATE reserva
     SET motivo_cancelamento  = 'Registro de teste atualizado pela Sprint 3',
         antecedencia_minutos = 15,
         eta_origem           = 'manual',
         eta_minutos          = 12,
         eta_atualizado_em    = SYSTIMESTAMP
   WHERE id = v_reserva_id;

  DELETE FROM reserva
   WHERE id = v_reserva_id;

  COMMIT;

  DBMS_OUTPUT.PUT_LINE('Reserva de teste usada na auditoria: ' || v_reserva_id);
END;
/

-- ----------------------------------------------------------------------------
-- CONSULTA FINAL
-- Exibe os registros mais recentes da auditoria
-- ----------------------------------------------------------------------------
PROMPT ========================================
PROMPT CONSULTA FINAL DA AUDITORIA
PROMPT ========================================

SELECT id,
       reserva_id,
       operacao,
       usuario_banco,
       TO_CHAR(data_operacao, 'YYYY-MM-DD HH24:MI:SS TZH:TZM') AS data_operacao,
       DBMS_LOB.SUBSTR(dados_old, 4000, 1) AS dados_old,
       DBMS_LOB.SUBSTR(dados_new, 4000, 1) AS dados_new
  FROM auditoria_reserva_s3
 ORDER BY id DESC
 FETCH FIRST 10 ROWS ONLY;

